### PR TITLE
#25: Fix long error messages clipping on apply scene

### LINKED ISSUE #25: Failed download messages can be cut off
An example of trying to download `MoarFactory`, a very outdated mod.

Image

### PR DESCRIPTION
**Pull request by surdaft**
Implemented a utility function which you provide a max width and it will wrap within it. I encountered issues with using just the root width and the overall with was extremely narrow, so I instead use 80% of the root width.

I can foresee there potentially being an issue where it is _too narrow_, however I feel that at that point the system is already too narrow for effective use anyway.

Fixes #25 where error messages get cut off due to long URLs or paths.

image

### CODE REVIEW

**Comment by budak7273** [comment]
I can confirm this successfully wraps the same error I encountered when making the original issue report
image

It does look like it can still be cut off by some smaller terminals... unless this is just VSCode incorrectly reporting terminal width to the program?
image

**Review by budak7273 — CHANGES_REQUESTED** [review]
Code looks good, but it looks like it's affecting Windows Terminal as well
image

Are you able to reproduce the problem on your end?

**Comment by surdaft** [comment]
I haven't been able to reproduce it but I was testing on linux with a dedicated server instance. I'll try with windows later. I see the issue is filepaths, half thought about that issue, it has no space so I'll have to hard break it, or I can get the instance path and trim the info up to the instance path out

**Review by budak7273 — CHANGES_REQUESTED** [review]
It looks like the changes to the wrapping are removing spaces from the error message
image

**Comment by surdaft** [comment]
image

I have rewritten how it handles file paths so that it is more consistent, it looks to be good with your error. The error itself looks like your local env has 2 things trying to grab that zip file, do you potentially use a local test version of the API?

**Comment by budak7273** [comment]
image
image

Looks good even on quite tiny screens. Thanks for your contributions!

I don't actually know what is causing that error locally, I don't host my own version of the API, and that's the only mod that results in that error for me.

**Review by budak7273 — APPROVED** [review]

**Review by Vilsol — CHANGES_REQUESTED** [review]
IMO The blind reversal of all slashes could be an issue, as Windows users (and Windows itself) expect that format.

I would also suggest changing the way splitting works in general. This is not a must, but I would make a loop until we've processed the entire string. In the loop we pick a pointer where we would ideally want to split the string, and then backtrack until we encounter a space or a slash (forwards or back). If we can't find one for N (idk pick some sane default) characters, we had-split where we wanted to in the first place. Repeat until end of string is reached.

**Comment by Vilsol** [comment]
@surdaft please run the linter and commit it

**Review by Vilsol — APPROVED** [review]

**Pull request merged**
